/**
 * Generated by packages/sim/scripts/generate-master-dps.mjs from the
 * deterministic 20-second authoritative Master Damage Lab. Do not hand-edit;
 * rerun the generator after changing a Master profile or combat semantics.
 */

export const MASTER_DPS = Object.freeze({
  'porcupine-quills': 563.204,
  'puffer-pouch': 0,
  'electric-eel-coil': 91,
  'firefly-colony': 48,
  'mantis-scythes': 2259,
  'gecko-pads': 2899.035,
  'owl-pinions': 94.225,
  'bat-ears': 0,
  'crab-pincers': 1040,
  'armadillo-greaves': 0,
  'skunk-brush': 3010.176,
  'monarch-brood': 16,
} as const);

export type MasterDpsTraitId = keyof typeof MASTER_DPS;

const MASTER_DPS_VALUES: readonly number[] = Object.values(MASTER_DPS);

/** Stable generated-content input consumed by the runtime/replay fingerprint. */
export const MASTER_DPS_FINGERPRINT_INPUT = Object.entries(MASTER_DPS)
  .map(([traitId, dps]) => `${traitId}:${dps}`)
  .join('|');

export const MEAN_MASTER_DPS = MASTER_DPS_VALUES
  .reduce((total, value) => total + value, 0) / MASTER_DPS_VALUES.length;
